#!/bin/sh

if [ -e /tmp/Sophos\ Installer.app/Contents/MacOS/Sophos\ Installer ]
then
    /tmp/Sophos\ Installer.app/Contents/MacOS/Sophos\ Installer --install
else
    echo "Expected Sophos installer app at /tmp/Sophos\ Installer.app, not found"
    exit 1
fi