#!/bin/sh

INSTALLER_PATH="/tmp/Sophos\ Installer.app/Contents/MacOS/Sophos\ Installer"

if [ -e $INSTALLER_PATH ]
then
    "$INSTALLER_PATH" --install
else
    echo "Expected Sophos installer app at /tmp/Sophos\ Installer.app, not found"
    exit 1
fi